### ISSUE TITLE
Possible to add DocIDs as bookmark names?

### ISSUE THREAD

**Issue by ccastillo-id** [Nuix/Export-Family-PDFs#2]
There is a Add Bookmarks checkbox that will add bookmark of the attachment's file name. is there a way to use the attachment's docid instead as well?

I tried altering the ExportFamilyPDFs.rb file from

**Old**
PdfMerger.merge(final_output_file,input_files,add_bookmarks,group.map{|i|i.getLocalisedName})

**Attempt**
productionSetItems = group.map{|i|i.get_production_set_items}
PdfMerger.merge(final_output_file,input_files,add_bookmarks,productionSetItems.map { |i| i.getDocumentNumber }.join(""))

But no avail

**Comment by JuicyDragon** [comment]
Hello @ccastillo-id,

I think you are really close.  The issue I believe stems from this line in your version:
```ruby
productionSetItems = group.map{|i|i.get_production_set_items}
```

For each item, that returns a `Set<ProductionSetItem>`.  While your logic is treating it as though the result is this:
```ruby
productionSetItems = [
  ProductionSetItem,
  ProductionSetItem,
  ProductionSetItem,
  ProductionSetItem,
]
```

I believe conceptually it's more like this:
```ruby
productionSetItems = [
  [ProductionSetItem],
  [ProductionSetItem],
  [ProductionSetItem],
  [ProductionSetItem],
]
```

Or it could even possibly be more like this if some items have no production set items and others have more than 1:
```ruby
productionSetItems = [
  [ProductionSetItem,ProductionSetItem],
  [],
  [ProductionSetItem],
  [ProductionSetItem],
]
```

I believe if you modify it a bit to the following you should get the result you are looking for:
```ruby
bookmark_titles = group.map do |item|
	psis = item.getProductionSetItems
	doc_nums = psis.map{|psi| psi.getDocumentNumber.toString }
	next doc_nums.join(";")
end

PdfMerger.merge(final_output_file,input_files,add_bookmarks,bookmark_titles)
```

Let me know if you have questions about that.  I know I had to think about it a bit myself and even re-write it once as my first attempt didn't quite approach it right.

**Comment by ccastillo-id** [comment]
The error I'm getting with changing it to this is...

Export Directory: C:\Users\srvnuix\Desktop\OUTPUT
Exporting temporary PDFs: native
Exporting temporary PDFs: native
Exporting temporary PDFs: pdf
Exporting temporary PDFs: pdf
Exporting temporary PDFs: pdf
Exporting temporary PDFs: pdf
Exporting temporary PDFs: stamping
Exporting temporary PDFs: stamping
Exporting temporary PDFs: digest
Family Groups: 234
Generating combined PDFs...
Merging 1 PDFs into single PDF: REV00000001.pdf
Error occured in provided block:
(RuntimeError) Error while creating output file directories: undefined method `mkdirs' for nil:NilClass
output_file: REV00000001.pdf
input_files: C:\Users\srvnuix\Desktop\OUTPUT\_Temp_\PDFs\e59\e595afc8-fb4f-46d7-9a2a-023b3d8919b9.pdf
org.jruby.exceptions.RuntimeError: (RuntimeError) Error while creating output file directories: undefined method `mkdirs' for nil:NilClass
output_file: REV00000001.pdf
input_files: C:\Users\srvnuix\Desktop\OUTPUT\_Temp_\PDFs\e59\e595afc8-fb4f-46d7-9a2a-023b3d8919b9.pdf
	at RUBY.merge(C:/ProgramData/Nuix/Scripts/ExportFamilyPDFs_v1.14.0/ExportFamilyPDFs.nuixscript/PdfMerger.rb:19)
	at RUBY.<main>(C:\ProgramData\Nuix\Scripts\ExportFamilyPDFs_v1.14.0\ExportFamilyPDFs.nuixscript\ExportFamilyPDFs.rb:564)
	at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1809)
	at org.jruby.RubyEnumerable.each_with_index(org/jruby/RubyEnumerable.java:1258)
	at RUBY.<main>(C:\ProgramData\Nuix\Scripts\ExportFamilyPDFs_v1.14.0\ExportFamilyPDFs.nuixscript\ExportFamilyPDFs.rb:475)
	at RUBY.<main>(C:\ProgramData\Nuix\Scripts\ExportFamilyPDFs_v1.14.0\ExportFamilyPDFs.nuixscript\ExportFamilyPDFs.rb:281)


NEW CODE


				# Merge the PDFs
				# Depending on whether we used DAT for paths or found them manually we
				# determine the paths a little differently
				input_files = nil
				if export_dat
					input_files = group.map{|i|"#{temp_directory}\\#{pdf_lookup[i.getGuid]}"}
				else
					input_files = group.map{|i|pdf_lookup[i.getGuid]}
				end
				pd.logMessage("Merging #{group.size} PDFs into single PDF: #{final_output_file}")
				pd.logMessage("\tOutput filename modified to prevent overwriting existing combined PDF.") if final_output_file != output_file
				
				bookmark_titles = group.map do |item|
					psis = item.getProductionSetItems
					doc_nums = psis.map{|psi| psi.getDocumentNumber.toString }
					next doc_nums.join(";")
				end				
				
				PdfMerger.merge(final_output_file,input_files,add_bookmarks,bookmark_titles)

**Comment by ccastillo-id** [comment]
Interesting... when I add a slash in the File Name Template
![image](https://user-images.githubusercontent.com/71530530/116901707-1b63f080-abef-11eb-880c-2b1897c7c86b.png)
I get an Access is Denied error

**Comment by JuicyDragon** [comment]
I was just looking into what could cause this, but I see the issue now that you've included a screenshot.  Change it from 
```
\{docid}.pdf
```
to
```
{export_directory}\{docid}.pdf
```
The error message was happening on this line:
```ruby
java.io.File.new(output_file).getParentFile.mkdirs
```

When the template was resolving, it was just a file name without a directory, which causes `getParentFile` to return null and the `mkdirs` call to throw that error.

**Comment by ccastillo-id** [comment]
This works! Thanks!

**Comment by JuicyDragon** [comment]
Glad to hear it!
